// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqp2TwCtIiwP_mtbBLuVjhDxrjtPdtHBU',
    appId: '1:573300521024:web:b8c864e5f2899195ed87a5',
    messagingSenderId: '573300521024',
    projectId: 'calsync-a53ec',
    authDomain: 'calsync-a53ec.firebaseapp.com',
    storageBucket: 'calsync-a53ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV1LbhS8TnarzVOsZIqKxfBCuBxnGZs3U',
    appId: '1:573300521024:android:492c0e2d5cc4822bed87a5',
    messagingSenderId: '573300521024',
    projectId: 'calsync-a53ec',
    storageBucket: 'calsync-a53ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeqiDkbQyv_syDy2NcfCJWY4Sgc0np8Ss',
    appId: '1:573300521024:ios:85db62354629b8c2ed87a5',
    messagingSenderId: '573300521024',
    projectId: 'calsync-a53ec',
    storageBucket: 'calsync-a53ec.appspot.com',
    iosClientId:
        '573300521024-3sifpu4kisea22spv0ifshajbk2etlfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.calsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeqiDkbQyv_syDy2NcfCJWY4Sgc0np8Ss',
    appId: '1:573300521024:ios:85db62354629b8c2ed87a5',
    messagingSenderId: '573300521024',
    projectId: 'calsync-a53ec',
    storageBucket: 'calsync-a53ec.appspot.com',
    iosClientId:
        '573300521024-3sifpu4kisea22spv0ifshajbk2etlfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.calsync',
  );
}
