// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuXED5kRug24bPl-VSnOrA1ZOr24dpM0E',
    appId: '1:209176434525:web:06590a012d584805c07ab4',
    messagingSenderId: '209176434525',
    projectId: 'calendar-sync-project-369417',
    authDomain: 'calendar-sync-project-369417.firebaseapp.com',
    storageBucket: 'calendar-sync-project-369417.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYdrEH2Nh_ACSWVEpDzU5Q0ft5llOTgeU',
    appId: '1:209176434525:android:8352952b9ef438afc07ab4',
    messagingSenderId: '209176434525',
    projectId: 'calendar-sync-project-369417',
    storageBucket: 'calendar-sync-project-369417.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAllSINaPOvLvaZUTkOArHnIl2dWBqLYXY',
    appId: '1:209176434525:ios:27fca009295567bdc07ab4',
    messagingSenderId: '209176434525',
    projectId: 'calendar-sync-project-369417',
    storageBucket: 'calendar-sync-project-369417.appspot.com',
    androidClientId: '209176434525-8eqqripc8q688jsj38k056oathv2g7s5.apps.googleusercontent.com',
    iosClientId: '209176434525-jvffc44tf0qjocbrbjrmbib4mcdaipf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.calendarSync',
  );
}
